config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :charges

  resources :products do
    resources :comments, shallow: true
  end

  resources :line_items, only: [:create, :update, :destroy]
  delete "uploads/:id", to: "products#delete_image", :as => "uploads"

  get "cart", to: "line_items#cart"
  get "orders", to: "line_items#orders"

  root "products#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    if user_signed_in?
      @product = Product.find_by_id(params[:product_id])
      if !@product.blank?
        @comment = @product.comments.new(comment_params)
        @comment.user = current_user
        @comment.save
      else
        redirect_to products_url, alert: "Page not found!"
      end
    end
  end

  def destroy
    @comment.destroy
  end

  def edit
  end

  def update
    @comment.update(comment_params)
  end

  private

  def find_comment
    if user_signed_in?
      @comment = current_user.comments.find_by_id(params[:id])
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :product_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id='comment-<%= comment.id%>'>

  <div class="row">

    <div class="col-10">
      [<%=comment.created_at.strftime('%I:%M %P')%>]<%= comment.user.email%>:
      <%=comment.content%>
    </div>

    <div class="col-2">
      <% if current_user && current_user == comment.user %>

        <a href="<%= edit_comment_path(comment) %>" data-remote="true">
          <i class="fa fa-edit"></i>
        </a>

        <span> | </span>

        <a class="text-danger" href="<%= comment_path(comment) %>" data-remote="true" rel="nofollow"
        data-method="delete">
          <i class="fa fa-trash"></i>
        </a>

      <% end%>
    </div>

  </div>
</div>

app/views/comments/_commentForm.html.erb
<%=form_with model: [@product, @comment] do |f|%>
<div class="form-group">
    <%=f.text_field :content , class: 'form-control'%>
</div>
<%=f.submit 'Update'%>
<%= link_to 'Cancel', :back%>
<%end%>

app/views/comments/create.js.erb
$('#comment_div').prepend('<%= j render @comment%>');
$('#comment_body').val('')

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id%>').html('');

app/views/comments/edit.js.erb
$('#comment-<%= @comment.id%>').html('<%=j render "commentForm"%>');

app/views/comments/update.js.erb
$('#comment-<%= @comment.id%>').html('<%=j render "comment", comment:@comment %>');