config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :charges

  resources :products do
    resources :comments, shallow: true
  end

  resources :line_items, only: [:create, :update, :destroy]
  delete "uploads/:id", to: "products#delete_image", :as => "uploads"

  get "cart", to: "line_items#cart"
  get "orders", to: "line_items#orders"

  root "products#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  scope :cart_items, -> { where(item_state: "cart") }
  scope :order_items, -> { where(item_state: "order") }

  belongs_to :product
  belongs_to :user

  validates :user, presence: true
  validates :product, presence: true

  validates :quantity,
            numericality: { only_integer: true,
                            greater_than: 1, less_than_or_equal_to: :get_product_quantity }

  def get_product_quantity
    return self.product.quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :check_logged_in
  around_action :check_ownership, only: [:update, :destroy]

  def create
    product = Product.find_by_id(line_item_params[:product_id])
    if product.blank?
      redirect_to products_url, alert: "Unable to add the product to cart!"
      return
    end

    if product.user_id == current_user.id
      redirect_to product_url(product.id), alert: "You can't add your own product to the cart!"
      return
    end

    if product.quantity < 1
      redirect_to product_url(product.id), alert: "Product is not available at this time. Try again later!"
      return
    end

    if current_user.cart_items.where(product_id: product.id).exists?
      redirect_to product_url(product.id), alert: "Product is already in the cart!"
      return
    end

    @line_item = current_user.line_items.new(line_item_params)

    if @line_item.save
      redirect_to cart_url, notice: "Product was successfully added to cart."
      return
    else
      redirect_to products_url, alert: "Unable to add product to the cart."
    end
  end

  def update
    if @line_item.update(quantity: params[:quantity])
      redirect_to cart_url, notice: "Cart updated.", type: "success"
    else
      redirect_to cart_url, alert: "Unable to update the cart."
    end
  end

  def destroy
    @line_item.destroy
    redirect_to cart_url, notice: "Product was successfully removed from cart."
  end

  def cart
    @cart_items = current_user.cart_items.includes(:product)
    render "line_items/cart/index"
  end

  def orders
    @order_items = current_user.order_items.includes(:product).order(updated_at: :desc)
    render "line_items/orders/index"
  end

  private

  def check_logged_in
    if !user_signed_in?
      redirect_to products_url, alert: "Please Login!"
    end
  end

  def check_ownership
    @line_item = LineItem.cart_items.find_by_id(params[:id])
    if !@line_item.blank? && current_user.id == @line_item.user_id
      yield
    else
      redirect_to cart_url, alert: "Page not found!"
    end
  end

  def line_item_params
    params.require(:line_item).permit(:product_id, :quantity)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/cart/index.html.erb
<%= render  "layouts/notice" %>

<h1>Cart</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product Serail No</th>
      <th scope="col">Title</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col" colspan="2" class="text-center">Actions</th>
      <th scope="col">Total</th>

    </tr>
  </thead>

  <% grand_total = 0 %>
  <tbody>
    <% @cart_items.each do |item| %>
      <tr>
        <th scope="row"> <%= item.product.serial_no %> </th>
        <td> <%= item.product.title %> </td>
        <td> <%= item.product.price %> </td>
        <td> <%= item.quantity %> </td>
        <td>
          <a href="" data-toggle="modal" data-target="#exampleModal" data-title="<%= item.product.title %>"
                    data-item="<%= item.id %>" data-product_quantity="<%= item.product.quantity %>"
                    data-quantity="<%= item.quantity %>">Edit</a>
        </td>
        <td><%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% total = item.product.price * item.quantity %>
        <td> <%= total %> </td>

        <% grand_total += total %>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<div class="row">

  <div class="col">
    <h2>Grand Total: $<%= grand_total %> </h2>
    <br />
  </div>

  <div class="col ">
    <% if !current_user.cart_items.empty? %>
      <%= form_tag charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>

        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription"
            data-amount="500" data-locale="auto"></script>
      <% end %>
    <% end %>
  </div>

</div>

<br>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%=form_with url: line_items_url , method: "patch", id: "quantity_form", local: true do%>

        <div class="modal-body">
          <div class="form-group">
            <div class="row">
              <div class="col-4">
                <label for="recipient-name" class="col-form-label">Quantity: </label>
              </div>

              <div class="col-8">
                <input type="number" name="quantity" min="1" class="form-control" id="quantity">
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag('Save changes', class: 'btn btn-primary') %>

        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  var form;
  var path;
  $(document).ready(function () {
      form = $('#quantity_form');
      path = form.attr('action');
  });
  $('#exampleModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var title = button.data('title');
      var quantity = button.data('quantity');
      var id = button.data('item');
      var product_quantity = button.data('product_quantity');
  
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this);
      modal.find('.modal-title').text(title);
      modal.find('.modal-body input').val(quantity);
      modal.find('.modal-body input').attr('max', product_quantity);
  
      form.attr('action', path + "/" + id);
  })
</script>