config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :charges

  resources :products do
    resources :comments, shallow: true
  end

  resources :line_items, only: [:create, :update, :destroy]
  delete "uploads/:id", to: "products#delete_image", :as => "uploads"

  get "cart", to: "line_items#cart"
  get "orders", to: "line_items#orders"

  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many_attached :uploads

  validates :title, presence: true, length: { minimum: 5, maximum: 70 }
  validates :price, numericality: { greater_than: 0.00 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :serial_no, presence: true
  validates :user, presence: true

  before_validation :add_serial_no

  after_save ThinkingSphinx::RealTime.callback_for(:product)

  after_destroy :purge_uploads

  def add_serial_no
    self.serial_no = self.user_id.to_s + "-" + DateTime.now.strftime("%Y%m%d%H%M%S")
  end

  def purge_uploads
    self.uploads.purge_later
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :show, :destroy]
  around_action :check_ownership, only: [:edit, :update, :destroy]

  def index
    @products = Product.all.order(created_at: :desc)
    # @products = Product.search(params[:search])
  end

  def show
    @comment = Comment.new
    @line_item = LineItem.new
    @comments = @product.comments.order("created_at DESC")
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = current_user.products.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge_later

    redirect_to edit_product_url(image.record_id), notice: "Image Removed!"
  end

  private

  def find_product
    @product = Product.find_by_id(params[:id])
    if @product.blank?
      redirect_to products_url, alert: "Page not found!"
    end
  end

  def check_ownership
    if user_signed_in? && current_user.id == @product.user_id
      yield
    else
      redirect_to products_url, alert: "Page not found!"
    end
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, uploads: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_carousel.html.erb
<div id="slider" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
        <% count = 0 %>
        <% uploads.each do |upload| %>

        <% if count == 0 %>

        <li data-target="#slider" data-slide-to="<%= count %>" class="active"></li>

        <% else %>

        <li data-target="#slider" data-slide-to="<%= count %>"></li>

        <% end %>


        <% count += 1 %>
        <% end %>

    </ul>

    <!-- The slideshow -->
    <div class="carousel-inner">

        <% count = 0 %>
        <% uploads.each do |upload| %>

        <% if count == 0 %>

        <div class="carousel-item active">
            <%= image_tag upload, width: 1100, height: 500 %>
        </div>

        <% else %>

        <div class="carousel-item">
            <%= image_tag upload, width: 1100, height: 500 %>
        </div>

        <% end %>


        <% count += 1 %>
        <% end %>


    </div>

    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#slider" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#slider" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>

app/views/products/_form.html.erb
<div class="row justify-content-md-center">
  <div class="col-sm-4">
    <%= form_with(model: product, local: true) do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- Product => id, serial_no, title, description, price, quantity, user_id -->
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, autofocus: true, class: 'form-control', required: true, pattern:".{5,70}", title:"5 to 70 characters"%>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :price %>
        <%= form.number_field :price, step:'0.01', min:'0' , class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, min:'1', class: 'form-control', required: true %>
      </div>

      <div class="form-group">

        <% @product.uploads.each do |upload| %>
          <div class="row bg-light m-2 p-2 border border-secondary rounded">

            <div class="col-10">
              <%= image_tag upload, width:50, height:50 %>
            </div>

            <div class="col-2">

              <a class="text-danger" href="<%= uploads_path(upload.id) %>" rel="nofollow" data-method="delete">
                <i class="fa fa-trash"></i>
              </a>

            </div>

          </div>
        <% end %>

        <%= form.label :uploads %>
        <%= form.file_field :uploads, multiple: true, class: 'form-control', required: false %>
      </div>

      <div class="form-group">
        <%= form.submit 'Publish', class: 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>

app/views/products/edit.html.erb
<h1 class='text-center'>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render  "layouts/notice" %>

<h1>Products</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col" colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% count = 1 %>
    <% @products.each do |product| %>
    <tr>
      <th scope="row"> <%= count %> </th>
      <td> <%= product.title %> </td>
      <td> $<%= product.price %> </td>
      <td> <%= product.quantity %> </td>

      <% if user_signed_in? && current_user.id == product.user_id %>
      <td><%= link_to 'Show', product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>

      <td colspan="3" class="text-center"><%= link_to 'Show', product %></td>

      <% end %>
      <% count += 1 %>

    </tr>
    <% end %>
  </tbody>
</table>

<% if @products.empty? %>
<h1 class="text-center text-danger">
  Nothing Found!
</h1>
<% end %>
<br>

app/views/products/new.html.erb
<h1 class="text-center">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render "layouts/notice" %>
<% if user_signed_in? && current_user.id == @product.user_id %>
  <%= link_to 'Edit', edit_product_path(@product) %>
  | 
<% end %>
<%= link_to 'Back', products_path %>
<br />

<div class="row">

  <div class="col">
    <%= render 'carousel', uploads: @product.uploads%>
  </div>

  <div class="col">

    <h2> <%= @product.title %> </h2>
    <br />
    <p> <%= @product.description %> </p>
    <br />
    <p> Price: $<%= @product.price %> </p>
    <br />
    <p> Quantity: <%= @product.quantity %> </p>
    <% if user_signed_in? %>

      <% if current_user.id != @product.user_id %>

        <% if current_user.cart_items.where(product_id: @product.id).exists? %>
          <%= link_to "Already in cart", cart_path, class: 'btn btn-success' %>

        <% elsif @product.quantity < 1 %>
          <%= link_to "Sold Out", '#' , class: 'btn btn-danger disabled' %>

        <% else %>

          <%=form_with(model: @line_item, local:true) do |form|%>
            <%= form.hidden_field :product_id, value: @product.id%>
            <%= form.submit 'Add to cart', class: 'btn btn-warning' %>
          <% end %>

        <% end %>
        <br />
        <br />

        <%=form_with model: [@product,@comment] do |form|%>
          <div class="row">

            <div class="col-10">
              <div class="form-group">
                <%=form.text_field :content , class: 'form-control'%>
              </div>
            </div>

            <div class="col-2">
              <div class="form-group">
                <%= form.submit 'Comment', class: 'btn btn-primary' %>
              </div>
            </div>

          </div>

        <% end %>
      <% end %>
    <% end %>
    <div id="comment_div">
      <%@comments.each do |comment|%>
        <%= render 'comments/comment', comment:comment%>
      <%end%>

    </div>

  </div>

</div>