config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :charges

  resources :products do
    resources :comments, shallow: true
  end

  resources :line_items, only: [:create, :update, :destroy]
  delete "uploads/:id", to: "products#delete_image", :as => "uploads"

  get "cart", to: "line_items#cart"
  get "orders", to: "line_items#orders"

  root "products#index"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top">

    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <strong>
            <%= link_to 'S A B I T', root_path, class: 'navbar-brand' %>
        </strong>
        <%= render 'layouts/navigation_links' %>
    </div>

</nav>

app/views/layouts/_navigation_links.html.erb
<div class="navbar-nav">
    <%= render  "layouts/search_bar" %>
</div>
<% if user_signed_in? %>

<div class="navbar-nav ml-auto">

    <%= link_to 'Add Product', new_product_path, class: 'btn btn-bd-download d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3'%>

    <%= link_to current_user.email, edit_user_registration_path, class: 'nav-item nav-link'%>


    <a href="<%= cart_path %>" class='nav-item nav-link'>
        My Cart
        <span class="badge bg-warning">
            <% items = current_user.cart_items %>
            <% if items.empty? %>
            0
            <% else %>
            <%= items.length %>
            <% end %>
        </span>
    </a>
    <%= link_to 'My Orders',orders_path, class: 'nav-item nav-link'%>
    <%= link_to 'Logout',destroy_user_session_path, method: :delete, class: 'nav-item nav-link'%>

</div>

<% else %>

<div class="navbar-nav  ml-auto">
    <%= link_to 'Login', new_user_session_path, class: 'nav-item nav-link'%>
    <p class="nav-item nav-link">|</p>
    <%= link_to 'Signup', new_user_registration_path, class: 'nav-item nav-link'%>
</div>

<% end %>


<!-- <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Messages</a>
                    <div class="dropdown-menu">
                        <a href="#" class="dropdown-item">Inbox</a>
                        <a href="#" class="dropdown-item">Sent</a>
                        <a href="#" class="dropdown-item">Drafts</a>
                    </div>
                </div> -->

app/views/layouts/_notice.html.erb
<% if notice %>
<p class="alert alert-success" id="notice"><%= notice %></p>
<% end %>

<% if alert %>
<p class="alert alert-danger" id="notice"><%= alert %></p>
<% end %>

app/views/layouts/_search_bar.html.erb
<form action="<%= products_path %>" method="get">
    <div class="p-1 px-4 bg-light rounded rounded-pill shadow-sm">
        <div class="input-group">
            <input type="search" name='search' placeholder="What're you searching for?" aria-describedby="button-addon1"
                class="form-control border-0 bg-light">
            <div class="input-group-append">
                <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i
                        class="fa fa-search"></i></button>
            </div>
        </div>
    </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BasicDeviseIntegration523</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <%= render "layouts/navigation" %>
  </header>
  <main class='py-3'>
    <div class='container'>
      <%= yield %>
    </div>
  </main>
</body>

</html>